# Generated by Django 6.0.3 on 2026-03-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.CharField(default='Contact Us', max_length=100)),
                ('contact_phones', models.JSONField(blank=True, default=list)),
                ('contact_email', models.EmailField(max_length=254)),
                ('address_title', models.CharField(default='Address', max_length=100)),
                ('address', models.TextField()),
                ('location_title', models.CharField(default='Location', max_length=100)),
                ('map_url', models.URLField()),
                ('copyright_text', models.CharField(default='© 2026 Kuat. All rights reserved.', max_length=255)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
    ]
