# Generated by Django 6.0.3 on 2026-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our partners', max_length=120)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('partners', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Partners section',
                'verbose_name_plural': 'Partners section',
            },
        ),
    ]
